package interval

const (
	Seconds1  = Interval((uint(Second) << 8) | uint(1))
	Seconds2  = Interval((uint(Second) << 8) | uint(2))
	Seconds5  = Interval((uint(Second) << 8) | uint(5))
	Seconds10 = Interval((uint(Second) << 8) | uint(10))
	Seconds15 = Interval((uint(Second) << 8) | uint(15))
	Seconds30 = Interval((uint(Second) << 8) | uint(30))
	Seconds60 = Interval((uint(Second) << 8) | uint(60))
	Mins1     = Interval((uint(Minute) << 8) | uint(1))
	Mins2     = Interval((uint(Minute) << 8) | uint(2))
	Mins3     = Interval((uint(Minute) << 8) | uint(3))
	Mins5     = Interval((uint(Minute) << 8) | uint(5))
	Mins10    = Interval((uint(Minute) << 8) | uint(10))
	Mins15    = Interval((uint(Minute) << 8) | uint(15))
	Mins30    = Interval((uint(Minute) << 8) | uint(30))
	Mins60    = Interval((uint(Minute) << 8) | uint(60))
	Hours1    = Interval((uint(Hour) << 8) | uint(1))
	Hours2    = Interval((uint(Hour) << 8) | uint(2))
	Hours3    = Interval((uint(Hour) << 8) | uint(3))
	Hours4    = Interval((uint(Hour) << 8) | uint(4))
	Hours6    = Interval((uint(Hour) << 8) | uint(6))
	Hours8    = Interval((uint(Hour) << 8) | uint(8))
	Hours12   = Interval((uint(Hour) << 8) | uint(12))
	Hours24   = Interval((uint(Hour) << 8) | uint(24))
	Hours48   = Interval((uint(Hour) << 8) | uint(48))
	Days1     = Interval((uint(Day) << 8) | uint(1))
	Days2     = Interval((uint(Day) << 8) | uint(2))
	Days3     = Interval((uint(Day) << 8) | uint(3))
	Days7     = Interval((uint(Day) << 8) | uint(7))
	Weeks1    = Interval((uint(Week) << 8) | uint(1))
	Months1   = Interval((uint(Month) << 8) | uint(1))
	Years1    = Interval((uint(Year) << 8) | uint(1))
)
