package interval

const (
	Of1Second   = Interval((uint(Second) << 8) | uint(1))
	Of2Seconds  = Interval((uint(Second) << 8) | uint(2))
	Of5Seconds  = Interval((uint(Second) << 8) | uint(5))
	Of10Seconds = Interval((uint(Second) << 8) | uint(10))
	Of15Seconds = Interval((uint(Second) << 8) | uint(15))
	Of30Seconds = Interval((uint(Second) << 8) | uint(30))
	Of60Seconds = Interval((uint(Second) << 8) | uint(60))
	Of1Minute   = Interval((uint(Minute) << 8) | uint(1))
	Of2Minutes  = Interval((uint(Minute) << 8) | uint(2))
	Of3Minutes  = Interval((uint(Minute) << 8) | uint(3))
	Of5Minutes  = Interval((uint(Minute) << 8) | uint(5))
	Of10Minutes = Interval((uint(Minute) << 8) | uint(10))
	Of15Minutes = Interval((uint(Minute) << 8) | uint(15))
	Of30Minutes = Interval((uint(Minute) << 8) | uint(30))
	Of60Minutes = Interval((uint(Minute) << 8) | uint(60))
	Of1Hour     = Interval((uint(Hour) << 8) | uint(1))
	Of2Hours    = Interval((uint(Hour) << 8) | uint(2))
	Of3Hours    = Interval((uint(Hour) << 8) | uint(3))
	Of4Hours    = Interval((uint(Hour) << 8) | uint(4))
	Of6Hours    = Interval((uint(Hour) << 8) | uint(6))
	Of8Hours    = Interval((uint(Hour) << 8) | uint(8))
	Of12Hours   = Interval((uint(Hour) << 8) | uint(12))
	Of24Hours   = Interval((uint(Hour) << 8) | uint(24))
	Of48Hours   = Interval((uint(Hour) << 8) | uint(48))
	Of1Day      = Interval((uint(Day) << 8) | uint(1))
	Of2Days     = Interval((uint(Day) << 8) | uint(2))
	Of3Days     = Interval((uint(Day) << 8) | uint(3))
	Of7Days     = Interval((uint(Day) << 8) | uint(7))
	Of1Week     = Interval((uint(Week) << 8) | uint(1))
	Of1Month    = Interval((uint(Month) << 8) | uint(1))
	Of1Year     = Interval((uint(Year) << 8) | uint(1))
)
